"""empty message

Revision ID: dcb3885a337b
Revises: a5cffa318ac2
Create Date: 2024-01-20 18:20:56.047800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcb3885a337b'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('mass', sa.Integer(), nullable=True),
    sa.Column('hair_color', sa.String(length=45), nullable=True),
    sa.Column('skin_color', sa.String(length=45), nullable=True),
    sa.Column('eye_color', sa.String(length=45), nullable=True),
    sa.Column('birth_year', sa.String(length=45), nullable=True),
    sa.Column('gender', sa.String(length=45), nullable=True),
    sa.Column('homeworld', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('rotation_period', sa.String(length=45), nullable=True),
    sa.Column('orbital_period', sa.String(length=45), nullable=True),
    sa.Column('diameter', sa.String(length=45), nullable=True),
    sa.Column('climate', sa.String(length=45), nullable=True),
    sa.Column('gravity', sa.String(length=45), nullable=True),
    sa.Column('terrain', sa.String(length=45), nullable=True),
    sa.Column('surface_water', sa.String(length=45), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('planets_id', sa.Integer(), nullable=True),
    sa.Column('people_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['planets_id'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    op.drop_table('planets')
    op.drop_table('people')
    # ### end Alembic commands ###
